/**
 * src/utils/drillAttemptStorage.ts
 *
 * Attempt persistence layer for the v3.0 Generic Drill Engine.
 * Manages all read/write operations to localStorage under 'kdenz:drill-attempts'.
 *
 * This key is intentionally distinct from 'kdenz:drill-data' (technique/scenario
 * seed data managed by drill-storage.ts). Attempts are user-generated records;
 * seed data is app-bundled configuration.
 *
 * All functions are wrapped in try/catch — localStorage may be unavailable
 * (private browsing, storage quota exceeded, iframe restrictions). Errors are
 * logged as warnings and gracefully degraded to empty state.
 */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const ATTEMPTS_KEY = "kdenz:drill-attempts";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * A single scored attempt at a drill scenario.
 * Maps 1:1 to DrillEvaluationResult from drillEvaluationService.ts,
 * plus identity fields (who did it, when, for which technique/scenario).
 */
export type DrillAttempt = {
  /** Unique identifier — generated by generateAttemptId() */
  id: string;

  /** ISO 8601 timestamp of when the attempt was submitted */
  timestamp: string;

  /** ID of the technique practiced (e.g., 'mirroring', 'labeling') */
  techniqueId: string;

  /** ID of the scenario used (e.g., 'mirror-1', 'label-3') */
  scenarioId: string;

  /** The user's spoken/typed response */
  transcript: string;

  /** 0-100, computed via SyntaxRule pattern matching */
  formScore: number;

  /** 0-100 from Gemini, null if Gemini was unavailable */
  accuracyScore: number | null;

  /** 0-100 from Gemini, null if Gemini was unavailable */
  impactScore: number | null;

  /** Always 0 for Phase 20 isolated drills */
  timingScore: number;

  /**
   * Weighted composite:
   * - With Gemini: form*0.25 + accuracy*0.35 + impact*0.30 + timing*0.10
   * - Without Gemini: equals formScore
   */
  compositeScore: number;

  /** Coaching narrative from Gemini, or fallback text */
  explanation: string;

  /** false if Gemini failed or no API key was provided */
  geminiSucceeded: boolean;
};

/**
 * Lightweight session descriptor — tracks a single practice session
 * for a given technique (multiple scenarios/attempts within a sitting).
 */
export type DrillSession = {
  /** Session unique identifier */
  id: string;

  /** ISO 8601 timestamp when the session started */
  startTime: string;

  /** Technique being practiced in this session */
  techniqueId: string;

  /** Total number of attempts made in this session */
  attemptCount: number;

  /** Count of consecutive qualifying attempts (streak count) */
  streak: number;
};

// ---------------------------------------------------------------------------
// saveDrillAttempt
// ---------------------------------------------------------------------------

/**
 * Append a new attempt record to the stored attempts array.
 * Reads existing array, pushes new record, writes back.
 * Silently logs and ignores storage failures.
 */
export function saveDrillAttempt(attempt: DrillAttempt): void {
  try {
    const raw = localStorage.getItem(ATTEMPTS_KEY);
    const arr: DrillAttempt[] = raw ? (JSON.parse(raw) as DrillAttempt[]) : [];
    arr.push(attempt);
    localStorage.setItem(ATTEMPTS_KEY, JSON.stringify(arr));
  } catch (error) {
    console.warn("[DrillAttemptStorage] Failed to save attempt:", error);
  }
}

// ---------------------------------------------------------------------------
// getDrillAttempts
// ---------------------------------------------------------------------------

/**
 * Read stored drill attempts from localStorage.
 * Optionally filter to a specific technique.
 * Returns an empty array if nothing is stored or if parsing fails.
 */
export function getDrillAttempts(techniqueId?: string): DrillAttempt[] {
  try {
    const raw = localStorage.getItem(ATTEMPTS_KEY);
    if (!raw) return [];

    const arr = JSON.parse(raw) as DrillAttempt[];

    if (techniqueId !== undefined) {
      return arr.filter((a) => a.techniqueId === techniqueId);
    }

    return arr;
  } catch (error) {
    console.warn("[DrillAttemptStorage] Failed to read attempts:", error);
    return [];
  }
}

// ---------------------------------------------------------------------------
// getSessionStreak
// ---------------------------------------------------------------------------

/**
 * Compute the consecutive "streak" for a technique within the current session.
 *
 * A qualifying attempt is one where:
 * - formScore >= 80, AND
 * - accuracyScore >= 75 (if Gemini succeeded), OR
 * - accuracyScore is null (Gemini unavailable — use formScore alone)
 *
 * Streak is counted backwards from the most recent attempt, stopping at
 * the first non-qualifying attempt.
 *
 * @param techniqueId   - Only count attempts for this technique
 * @param sessionStartTime - ISO 8601 timestamp; only count attempts at or after this time
 */
export function getSessionStreak(
  techniqueId: string,
  sessionStartTime: string,
): number {
  try {
    const allAttempts = getDrillAttempts(techniqueId);

    // Filter to attempts within this session (timestamp >= sessionStartTime)
    const sessionAttempts = allAttempts.filter(
      (a) => a.timestamp >= sessionStartTime,
    );

    if (sessionAttempts.length === 0) return 0;

    // Sort by timestamp ascending (oldest first) to traverse in order
    const sorted = [...sessionAttempts].sort((a, b) =>
      a.timestamp.localeCompare(b.timestamp),
    );

    // Count consecutive qualifying attempts from the END of the array
    let streak = 0;
    for (let i = sorted.length - 1; i >= 0; i--) {
      const attempt = sorted[i];
      const formOk = attempt.formScore >= 80;

      let qualifies: boolean;
      if (attempt.accuracyScore !== null) {
        // Gemini succeeded — require both form and accuracy thresholds
        qualifies = formOk && attempt.accuracyScore >= 75;
      } else {
        // Gemini unavailable — use form score alone
        qualifies = formOk;
      }

      if (qualifies) {
        streak++;
      } else {
        // Streak broken — stop counting
        break;
      }
    }

    return streak;
  } catch (error) {
    console.warn("[DrillAttemptStorage] Failed to compute streak:", error);
    return 0;
  }
}

// ---------------------------------------------------------------------------
// generateAttemptId
// ---------------------------------------------------------------------------

/**
 * Generate a unique attempt ID.
 * Combines timestamp (base-36) with random suffix for uniqueness.
 * Example: "lve4k2abcde"
 */
export function generateAttemptId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
}

// ---------------------------------------------------------------------------
// clearDrillAttempts
// ---------------------------------------------------------------------------

/**
 * Remove all stored drill attempts from localStorage.
 * Used for dev reset in Phase 20; production will gate this behind auth.
 */
export function clearDrillAttempts(): void {
  try {
    localStorage.removeItem(ATTEMPTS_KEY);
  } catch (error) {
    console.warn("[DrillAttemptStorage] Failed to clear attempts:", error);
  }
}
